### ISSUE TITLE
No me funciona! (Solucionado)

### ISSUE THREAD

**Issue by ezar** [maincenter/Logotipos-TV#1]
He seguido los pasos pero no me funciona!

**Comment by KellerNET** [comment]
Hola, tengo que actualizar parte del "mini manual" es posible quedar para hablar por TeamSpeak3 o similar, me gustaría ayudarte a que te funcione.
Saludos.

**Comment by KellerNET** [comment]
Se me acaba de ocurrir que el manual puede estar un poco "lioso" y por consiguiente igual hago un Vídeo explicando el proceso bien.
Si me das uno o dos días intentaré tenerlo listo y añadiré el link del vídeo en la descripción inicial del repositorio.
Saludos.

**Comment by KellerNET** [comment]
Aquí te dejo el link al vídeo:
https://youtu.be/bbZBz3ltues
Cualquier cosa no dudes en comentarla.
Saludos y suerte.

**Comment by ezar** [comment]
Hola
He seguido varias veces el tutorial y el vídeo, pero siempre me genera la misma URL y claro con esa URL no va!
Está correctamente configurado la parte de PIC con la URL que pones.

![pic](https://cloud.githubusercontent.com/assets/42736/19362710/05362052-9188-11e6-8762-c0eeacdecd54.png)

**Comment by KellerNET** [comment]
Hola, tienes TeamSpeak 3 o puedes instalarlo? me encantaría charlar contigo por voz y resolver este problema, creo que tienes mal puesto algún valor, la URL que te está dando no empieza por http si no por picon. Si puedes instalar TeamSpeak 3 y tienes microfono, puedo mirarlo contigo, espero tu contestación.
Saludos

**Comment by KellerNET** [comment]
Si no tienes micro o no puedes hablar, envíame una captura de la sección picon a ver que puede estar fallando.

**Comment by ezar** [comment]
Adjunto la configuración:

![pic2](https://cloud.githubusercontent.com/assets/42736/19363017/19f4be94-9189-11e6-8344-136f8285a2cf.png)

**Comment by KellerNET** [comment]
Efectivamente lo tienes bien,
Vamos a ver, ve a Configuration, luego a General y luego a Image Cache.
Allí, pulsa en Clean image Cache y espera un minuto de relog "si le damos rápido se suele buguear" tras esperar este minuto, dale a Re-Fetch images y luego a Save.

**Comment by KellerNET** [comment]
Ahora ve a Configuration, Channel / EPG y luego a Channels.
Selecciona los canales con la tecla SHIFT presionada y pulsa en Reset Icon, luego dale a SAVE y a ver si te lo hace bien ahora.
Si no, la otra opción es que me dejes echarle un ojo de alguna manera, TeamViewer, Abriendo puerto para que acceda remotamente temporalmente o algo, ya que no se que puede ser lo que esté mal, para repasar todo bien.

**Comment by ezar** [comment]
Lo he arreglado. He actualizado la versión al ultimo build y ahora sí.
Muchas gracias!

**Comment by KellerNET** [comment]
Ok perfecto, sería un bug de esa versión.
De nada, si quieres que te añada los canales locales de tu comunidad, pasa me los nombres de los canales y en 3 o 4 días los tienes.
Saludos.

**Comment by ezar** [comment]
Muchas gracias.
Te paso los que falta y como los va a buscar
- 25TV: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/25_TV.png
- 3/24: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/3_24.png
- 8TV: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/8TV.png
- BTV: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/BTV.png
- TV3: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/TV3.png
- TV3HD: https://raw.githubusercontent.com/maincenter/Logotipos-TV/master/main/transparentes/TV3HD.png

Gracias.

**Comment by KellerNET** [comment]
Ok muchas gracias, te lo miro y te los preparo. Saludos.

**Comment by KellerNET** [comment]
Échale un ojo a ver que tal: https://github.com/maincenter/Logotipos-TV/commit/8cb5e8dbf6e41976204c20b78c077d6d4182bfc8
Tendrás que limpiar la cache, CONFIGURATION > GENERAL > IMAGE CACHE y pulsar en CLEAN IMAGE CACHE, esperar 1 minuto y luego pulsar en RE-FETCH IMAGES. ya me contarás a ver que tal están de calidad, creo que están perfectas, he probado antes en varios fondos y parecían estar correctas, aun que la de 8TV tiene una sombra propia del logo, ya me dirás a ver que tal le queda si no, busco alternativas.
Saludos.

**Comment by ezar** [comment]
Quedan perfectas!
César.

**Comment by KellerNET** [comment]
Buenas, ok, este fin de semana andaré liado pero intentaré terminartelos.
Saludos.

**Comment by KellerNET** [comment]
Buenas ezar, ya tienes los últimos logos que me pasaste disponibles, puedes mirarlos aquí https://github.com/maincenter/Logotipos-TV/commit/61bb43de727b48003816a4b20632262dd168fd00 Recuerda limpiar la Cache de TVHeadend, aun que pasados 24h creo que es, se te actualizarán solos.
Espero que se vean bien, alguno logos, TV L'Hospitalet, telebBadalona y BarçaTV no se encuentran en una buena resolución aun que he procurado dejarlos lo mas limpios posibles, si alguno se ve mal comentamelo he intentaré mejorarlo de alguna manera.
Saludos.

**Comment by ezar** [comment]
Se ven estupendamente! Vaya curro. Muchas gracias!

**Comment by KellerNET** [comment]
Me alegro que se vean bien, Gracias a ti por facilitarme estos datos.
Siendo solo uno el que gestiona todo esto tiene mas trabajo, esto lo hago en mi tiempo libre con el fin de dejar nuestros programas de reproducción, KODI, PLEX, ANDROIDTV, iOS lo mas chulos posibles, así que me alegro.
De todos modos creo que te faltarán algunos no? estas en Barcelona o alrededores y me a parecido ver que falta alguno de radio.... bueno sea como fuese, los logos que necesites pásalos y te los creo con mucho gusto.
Saludos.
